# Week 10: Matrices & SLAM

- Matrices & Transformation
- Simultaneous Localization and Mapping

## Matrices & Transformation

### Linear algebra gives you mini-spreadsheets for your math equations

Source: https://betterexplained.com/

![Algebra](images/algebra.jpg)


**Linear algebra: A tool to restore what is missing from broken parts** 

![Math](https://s3-ap-southeast-2.amazonaws.com/particle.com.au/app/uploads/2017/10/09153553/u5HhK.png)

In [1]:
## F(a*x) = a*F(x)
## F(x + y) = F(x) + F(y)

## F(x) = 2*x

## F(5*3) = 5*F(3)

print(2*(5*3))
print(5*(2*3))

30
30


In [2]:
## F(x) = x+3
print((5*3)+3)
print(5*(3+3))

18
30


![Multiple](https://betterexplained.com/wp-content/plugins/wp-latexrender/pictures/9ae605d8349f11e71a75b0c9cb849bc6.png)

![Multiple2](https://betterexplained.com/wp-content/plugins/wp-latexrender/pictures/495b6ea1b9badbcb0db15ceb21899159.png)

In [ ]:
distance = 10
velocity = 1

state = [distance, velocity]

Our equations as we usually right them:

$$
\begin{split}
{x_{t+1}} &= \color{royalblue}{x_t} + \Delta t &\color{royalblue}{v_t} \\
{v_{t+1}} &= &\color{royalblue}{v_t}
\end{split}
$$ 

The same equations using vectors and matrices:

![Matrix](images/matrix_mult.jpg)

![Mat](https://betterexplained.com/wp-content/uploads/images//linear-algebra-visualize-20121002-221620.png)



It's as if we were taking a cup of input data and pouring it into our equations to get the result:

![Pour](https://betterexplained.com/wp-content/uploads/images//linear-algebra-pour-20121002-220550.png)

In [7]:
import numpy as np

a = np.array([4,5,6])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(a, '\n')
print(B)
a.dot(B)

[4 5 6] 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([4, 5, 6])

In [8]:
C = np.array([[1,0,0],[0,0,1],[0,1,0]])

print(a, '\n')
print(C)
a.dot(C)

[4 5 6] 

[[1 0 0]
 [0 0 1]
 [0 1 0]]


array([4, 6, 5])

Our operations matrix transforms our input vector (or input matrix):

![Matrix prediction](https://www.bzarg.com/wp-content/uploads/2015/08/gauss_8-300x276.jpg)

What about the transpose and the inverse?

![Transpose](https://betterexplained.com/wp-content/uploads/linear-algebra/x-transform-x.png)

In [9]:
5*(1/5)

0.2

## SLAM

![Constraints](images/constraints.jpg)

SLAM
- Landmark extraction
- Data association
- State estimation
- State update
- Landmark update

![Process](images/ekf_slam.jpg)

Source: https://dspace.mit.edu

Previous position:
![1](images/1.jpg)

Moves and predicts new position:
![2](images/2.jpg)

Scans environment to find landmarks:
![3](images/3.jpg)

Uses measurements to update/correct the position estimate:
![4](images/4.jpg)

**Landmarks** should be:
- Easily re-observable
- Unique (distinguishable)
- Plentiful
- Stationary


What can we use as landmarks here?

![Room](https://www.distant-horizons.de/blog/03_last_preparations/apartment.jpg)

SLAM steps in more detail:

- **Landmark Extraction**

- **Data Association**
    - We might not re-observe landmarks at every time step
    - We might observe something as being a landmakr but fail to ever see it again
    - We might wrongly associate a landmark to a previosuly seen landmark

- **State Estimation and State Update**

- **Landmark Update**

The state now becomes more complex, luckily we have our vectors to handle this:

![new state](images/state.jpg)